### PR TITLE
Multiple certificates

### PR DESCRIPTION
**Pull request by Ph0tonic**

### CODE REVIEW

**Review by volodymyrss — CHANGES_REQUESTED** [review]
could you ads it to CLI?

also, give admin an option to specify user to save

**Comment by Ph0tonic** [comment]
I propose that we create a new issue for the admin idea so we can already merge this and work on this additional part.

**Comment by volodymyrss** [comment]
> I propose that we create a new issue for the admin idea so we can already merge this and work on this additional part.

Ok please create an issue and then merge this one.

**Review by volodymyrss — APPROVED** [review]
please make an issue and refer to it here. Thanks!

**Comment by Ph0tonic** [comment]
> please make an issue and refer to it here. Thanks!

See #36

**Pull request merged**
